name: df
description: Convert numbers!
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: any
  harpo:
    git: https://github.com/iamtheblackunicorn/Harpo.git
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Ostrich
      fonts:
        - asset: assets/fonts/Ostrich.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
