name: df
description: Convert numbers!
publish_to: 'none'
version: 1.1.0+2
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  harpo: ^2.1.0
  termstyle: ^1.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Ostrich
      fonts:
        - asset: assets/fonts/Ostrich.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
